// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddymlnqcguddsnkayiqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkeW1sbnFjZ3VkZHNua2F5aXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjg0NTcsImV4cCI6MjA2NTY0NDQ1N30.a8M_nH_5A0E8FyL-xFS78YWYJ8LYkQs0fhlvdvr2N6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);